version: 2.1

workflows:
  version: 2
  ci:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: 'python:3.10-slim'
    steps:
      - checkout
      - run: zip -r thangs-blender-addon.zip . -x@exclude.lst
      - store-artifacts:
          path: thangs-blender-addon.zip