version: 2.1

workflows:
  version: 2
  ci:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: 'python:3.11'
    steps:
      - checkout
      - run: apt-get update && apt-get -y install rsync zip
      - run: make build-package-dev
      - store_artifacts:
          path: .build/thangs-blender-addon.zip