version: 2.1

workflows:
  version: 2
  ci:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: 'python:3.10-slim'
    steps:
      - checkout
      - run: pwd
      - run: apt-get update && apt-get -y install rsync
      - run: make build-package
      - store_artifacts:
          path: build/thangs-blender-addon/thangs-blender-addon.zip